### PR TITLE
feat: add ingressClassName

### PR DESCRIPTION
**Pull request by lenglet-k**
Kubernetes Ingress need ingressClassName. So we must set this parameter in helm chart.

### CODE REVIEW

**Comment by lenglet-k** [comment]
Hello,

No problem. How you run your test ?

**Comment by lenglet-k** [comment]
> Hello,
> 
> required items:
> 
>     1. values schema + lint test
> 
>     2. unit test

I have do it:

`helm lint .
==> Linting .

1 chart(s) linted, 0 chart(s) failed
`

`
just test-helm
helm plugin ls | grep unittest || helm plugin install https://github.com/helm-unittest/helm-unittest.git
unittest	0.3.6  	Unit test for helm chart in YAML with ease to keep your chart functional and robust.
helm unittest -f 'test/unit/*.yaml' .

### Chart [ apicurio-registry ] .

 PASS  test deployment-registry.yaml template	test/unit/deployment_registry.yaml
 PASS  test deployment-sync.yaml template	test/unit/deployment_sync.yaml
 PASS  test ingress	test/unit/ingress.yaml
 PASS  test sa	test/unit/sa.yaml

Charts:      1 passed, 1 total
Test Suites: 4 passed, 4 total
Tests:       23 passed, 23 total
Snapshot:    0 passed, 0 total
Time:        46.900894ms
`

**Review by eshepelyuk — CHANGES_REQUESTED** [review]
plz
1. add lint test case for a new property
1. rebase and squash a PR into single commit

**Comment by lenglet-k** [comment]
Hello, @eshepelyuk  it's done.

**Comment by eshepelyuk** [comment]
Thank you 
will be available in
https://github.com/eshepelyuk/apicurio-registry-helm/releases/tag/3.3.0

**Pull request merged**
